### ISSUE TITLE
Set a User Agent when making requests to Bugzilla's API

### ISSUE THREAD

**Issue by edmorley** [klahnakoski/MoDevLibrary#2]
It's best practice to set an informative User Agent when making requests to an external API, and helps those maintaining the API track the sources of inefficient queries/heavy load :-)

https://github.com/klahnakoski/MoDevLibrary/blob/master/base/modevlib/rest/BugzillaClient.js

**Comment by klahnakoski** [comment]
Since the code is called from the browser, and not allowed [1], maybe you can suggest another common header.

[1] https://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader()-method

**Comment by edmorley** [comment]
It is allowed now:
https://bugzilla.mozilla.org/show_bug.cgi?id=1188932#c22

**Comment by klahnakoski** [comment]
It figures.
