### ISSUE TITLE
Switch from BzAPI to the Bugzilla native REST API

### ISSUE THREAD

**Issue by edmorley** [klahnakoski/MoDevLibrary#3]
Since the former is deprecated and 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804

https://github.com/klahnakoski/MoDevLibrary/blob/master/base/modevlib/rest/BugzillaClient.js

**Comment by klahnakoski** [comment]
The dead code is cut out, and a warning added.   This code is in only a few low-usage dashboards; when any need an update I will review what's required to remove bzAPI completely.
